[package]
name = "lingo"
version = "0.1.2"
edition = "2021"

[dependencies]

clap = { version = "4.1", features = ["derive"] }
os-version = "0.2"

serde = "*"
serde_json = "*"
serde_derive = "*"
which = "*"

toml = {version = "0"}
crossbeam = "*"

termion = "1.5"
git2 = "*"
run_script = "0.10"
