[package]
name = "lingo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = { version = "3.1", features = ["derive"] }
os-version = "0.2"

regex = "1"
serde = "*"

serde_json = "*"
serde_derive = "*"

toml = {version = "0.5"}
crossbeam = "*"

termion = "1.5"
git2 = "*"
run_script = "0.10"
